### ISSUE TITLE
Issue running a script

### ISSUE THREAD

**Issue by lgarby** [jamietsao/slack-multi-channel-invite#13]
Hello Jamie, thanks for building this. I am new to go and having issues running the script. Could you provide some more guidance or detailed instructions?  App is created in slack, permissions assigned, approved by IT and laugh token generated. Golang installed via  homebrew on Mac, repo is downloaded locally and shell is in pwd. Issue the command with attributes filled in and get an error. Assume I need a go run <script> or something along those lines?

**Comment by jamietsao** [comment]
@lgarby - Sorry just seeing this now.  Any luck getting this to run?  The README for this repo has fairly detailed instructions.  Can you post the error you are getting?

**Comment by lgarby** [comment]
Got it all sorted out.  Thanks for reaching out.

Regards,
Loren

**Comment by jamietsao** [comment]
Awesome - great to hear!
