### ISSUE TITLE
Bulk List

### ISSUE THREAD

**Issue by bart1287** [jamietsao/slack-multi-channel-invite#4]
Is there a way we can bulk add users instead of one user at a time?  I just figured out how to run this with go and it works great!

Thanks so much for putting this together

**Comment by jamietsao** [comment]
Adding bulk user support should be straightforward.  I'll try to add that soon.

**Comment by bart1287** [comment]
Thanks, Jaime!  Looking forward to testing it out as this will save me a ton of time!

**Comment by jamietsao** [comment]
@bart1287 - Done!  I just published a new `v1.0.0` release with bulk user support: https://github.com/jamietsao/slack-multi-channel-invite/releases/tag/v1.0.0

If you would be so kind, starring this repo would be much appreciated!

**Comment by bart1287** [comment]
Starred it!  Thanks so much for getting that added so quickly.

**Comment by bart1287** [comment]
Just got a chance to test this out!  Works great!  Thanks so much for adding this in so quickly!

**Comment by jamietsao** [comment]
Awesome, glad to hear!
