### ISSUE TITLE
Invalid_auth error

### ISSUE THREAD

**Issue by ekrusz** [jamietsao/slack-multi-channel-invite#6]
I am getting an "invalid_auth" error when executing the command: **slack-multi-channel-invite -api_token=xoxp-... -emails=email@email.com -channels=channelname1 -private=true.** Is there something wrong with my syntax?

Looking up users ...
usersLookupByEmailResponse: {Ok:false User:{ID: Name:} Error:invalid_auth}
Error while looking up user with email  Non-ok response while looking up user by email
conversationsListResponse: {Ok:false Channels:[] ResponseMetadata:{NextCursor:} Error:invalid_auth Needed: Provided:}panic: Non-ok response while querying list of channels

**Comment by jamietsao** [comment]
Your syntax looks fine to me.  `invalid_auth` implies a bad token.  Are you sure the token is a valid one from a Slack app in your workspace?  Not sure if related to permission scopes but make sure to add the correct scopes listed in README.

**Comment by jtc267** [comment]
I have the same issue!

**Comment by jamietsao** [comment]
@ekrusz - Did you ever get this working?  I'll try this with a new Slack App to see if I can reproduce.

**Comment by ekrusz** [comment]
I am afraid I was never able to get past the error.

**Comment by jamietsao** [comment]
UPDATE

It appears Slack has changed something about how access tokens work (now you can configure bot tokens or user tokens).  I tried creating a new app and added the required permission scopes but was also getting the same `invalid_auth` error you two are seeing (tried both bot and user tokens).  

My previous app's token still works.  When I look at that app, there's a message in the header that says:
```
Slack has improved how we handle permissions for apps, so you can now request only the specific scopes your app needs. We recommend updating your app’s scopes.
```
I haven't done that as I'm pretty sure it'll break my previous token.

I'll continue digging and hopefully find a solution.  Thanks for your patience.

**Comment by jamietsao** [comment]
@ekrusz @jtc267 

I believe I have fixed the issue.  Use the latest release: https://github.com/jamietsao/slack-multi-channel-invite/releases/tag/v1.1.0

Let me know if you're still running into problems

**Comment by ekrusz** [comment]
Excellent thank you @jamietsao/slack-multi-channel-invite
***@***.***> !
