### ISSUE TITLE
I love this script, but would it be possible to expand with remove?

### ISSUE THREAD

**Issue by vongohren** [jamietsao/slack-multi-channel-invite#8]
Hey! I have been using this for a while for my onboarding, but I would love to have the possibility to off board as well?

Im not a go writer so cannot see the immediate way to fix this, but for a go writer, it might be a quick fix? Reusing the same mechanisms as invite but calling a seperate url?

**Comment by jamietsao** [comment]
Hi @vongohren - Can you provide more details into your offboarding use case?  Would the person not just be removed/deactivated from the Slack org and thus offboarded by default?

**Comment by vongohren** [comment]
So what we do is that we have a list of channels that is private because we
use a community slack.
So in the onboarding docs there is a pointer to the script to run, with all
defined channels.
But now I have to go and remove from all private channels manually.
It would be great if I just could have a point to a script with the same
channels to remove from, "remove_user email channel1,channel2,channel3"

**Comment by vongohren** [comment]
@jamietsao I see that I forgot to at you but maybe you get the message after all?

**Comment by jamietsao** [comment]
Hi @vongohren - Yes, I saw your message.  I'll take a look at implementing this when I have a free moment.

**Comment by vongohren** [comment]
That would be cool, let me know if I can assist in any way!

**Comment by jamietsao** [comment]
@vongohren - I just added this ability in latest release: https://github.com/jamietsao/slack-multi-channel-invite/releases/tag/v1.2.0

Just need to set optional `action` flag to `remove`.  See README for example.

**Comment by vongohren** [comment]
Nice! Thanks alot for that!
